### ISSUE TITLE
Connection error use azure embedding

### ISSUE THREAD

**Issue by cxy-gpt** [langchain-ai/langchain-postgres#43]
connection = "postgresql+psycopg://YYY:XXXX@localhost/ZZZ"
collection_name = "my_docs"
from langchain_postgres import PGVector
from langchain_postgres.vectorstores import PGVector

vectorstore = PGVector(
    embeddings=embeddings,
    collection_name=collection_name,
    connection=connection,
    use_jsonb=True,
)
db = vectorstore.from_texts(    ["communication"], embeddings)

    db = vectorstore.from_texts(    ["communication"], embeddings)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/site-packages/langchain_postgres/vectorstores.py", line 975, in from_texts
    return cls.__from(
           ^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/site-packages/langchain_postgres/vectorstores.py", line 438, in __from
    store = cls(
            ^^^^
  File "/usr/local/anaconda3/lib/python3.11/site-packages/langchain_postgres/vectorstores.py", line 295, in __init__
    raise ValueError(
ValueError: connection should be a connection string or an instance of sqlalchemy.engine.Engine
Exception ignored in: <function PGVector.__del__ at 0x7fdf7b19dda0>
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.11/site-packages/langchain_postgres/vectorstores.py", line 326, in __del__
    if isinstance(self._engine, sqlalchemy.engine.Connection):
                  ^^^^^^^^^^^^
AttributeError: 'PGVector' object has no attribute '_engine'

**Comment by evahbe** [comment]
I think it is because it is not detecting correctly the 'connection_string' parameter, try checking and varying it, mostly adding/removing the "+psycopg" part, for me it kinda worked. Got some other error after, but at least not that one any more!

**Comment by eyurtsev** [comment]
This looks like some tear down race condition. It's triggered on __del__ . You can probably explicitly invoke del on the vectorstore as a work-around for now
